//
// Created by m36 on 08/09/23.
//

#ifndef LABORATORIOPROGRAMMAZIONE_SIANIMARCO_OBSERVER_H
#define LABORATORIOPROGRAMMAZIONE_SIANIMARCO_OBSERVER_H

#endif //LABORATORIOPROGRAMMAZIONE_SIANIMARCO_OBSERVER_H
